"""
Predictor — ML/DL time series forecasting service.

Supported models:
  linear  — Linear Regression
  ridge   — Ridge Regression
  lasso   — Lasso Regression
  svr     — Support Vector Regression
  rf      — Random Forest Regressor
  gb      — Gradient Boosting Regressor
  mlp     — MLP Neural Network (MLPRegressor)
  lstm    — LSTM Neural Network (TensorFlow/Keras)

Approach: sliding-window supervised learning.
Last `lookback` values → predict next value.
Trains on first (1-test_split) of windows, tests on rest.
Future values generated by recursive single-step prediction.
"""

from __future__ import annotations
import numpy as np
from typing import Any


def _make_windows(values: np.ndarray, lookback: int):
    """Create supervised learning dataset from time series."""
    X, y = [], []
    for i in range(len(values) - lookback):
        X.append(values[i : i + lookback])
        y.append(values[i + lookback])
    return np.array(X), np.array(y)


def _build_model(model_name: str, hp: dict) -> Any:
    from sklearn.linear_model import LinearRegression, Ridge, Lasso
    from sklearn.svm import SVR
    from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
    from sklearn.neural_network import MLPRegressor

    if model_name == "linear":
        return LinearRegression()

    elif model_name == "ridge":
        return Ridge(alpha=float(hp.get("alpha", 1.0)))

    elif model_name == "lasso":
        return Lasso(alpha=float(hp.get("alpha", 0.1)), max_iter=3000)

    elif model_name == "svr":
        return SVR(
            C=float(hp.get("C", 1.0)),
            kernel=str(hp.get("kernel", "rbf")),
            epsilon=float(hp.get("epsilon", 0.1)),
        )

    elif model_name == "rf":
        md = hp.get("max_depth")
        return RandomForestRegressor(
            n_estimators=int(hp.get("n_estimators", 100)),
            max_depth=int(md) if md else None,
            random_state=42,
            n_jobs=-1,
        )

    elif model_name == "gb":
        return GradientBoostingRegressor(
            n_estimators=int(hp.get("n_estimators", 100)),
            learning_rate=float(hp.get("learning_rate", 0.1)),
            max_depth=int(hp.get("max_depth", 3)),
            random_state=42,
        )

    elif model_name == "mlp":
        hl_str = str(hp.get("hidden_layer_sizes", "64,32"))
        hidden_layers = tuple(
            int(x.strip()) for x in hl_str.split(",") if x.strip().isdigit()
        )
        if not hidden_layers:
            hidden_layers = (64, 32)
        return MLPRegressor(
            hidden_layer_sizes=hidden_layers,
            max_iter=int(hp.get("max_iter", 500)),
            random_state=42,
            early_stopping=True,
            n_iter_no_change=20,
        )

    return LinearRegression()


def _suggest_params(trial, model_name: str) -> dict:
    """Return Optuna-suggested hyperparameters for the given model."""
    if model_name == "linear":
        return {}
    elif model_name in ("ridge", "lasso"):
        return {"alpha": trial.suggest_float("alpha", 1e-3, 100.0, log=True)}
    elif model_name == "svr":
        return {
            "C": trial.suggest_float("C", 0.01, 100.0, log=True),
            "kernel": trial.suggest_categorical("kernel", ["rbf", "linear"]),
            "epsilon": trial.suggest_float("epsilon", 0.001, 1.0, log=True),
        }
    elif model_name == "rf":
        return {
            "n_estimators": trial.suggest_int("n_estimators", 30, 300),
            "max_depth": trial.suggest_int("max_depth", 2, 15),
        }
    elif model_name == "gb":
        return {
            "n_estimators": trial.suggest_int("n_estimators", 30, 200),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "max_depth": trial.suggest_int("max_depth", 2, 6),
        }
    elif model_name == "mlp":
        n_layers = trial.suggest_int("n_layers", 1, 3)
        sizes = [trial.suggest_int(f"units_{i}", 16, 256) for i in range(n_layers)]
        return {
            "hidden_layer_sizes": ",".join(str(s) for s in sizes),
            "max_iter": trial.suggest_int("max_iter", 200, 1000),
        }
    return {}


def tune_and_predict(
    values: list[float],
    labels: list[str],
    model_name: str,
    base_hp: dict,
) -> dict:
    """
    Optuna hyperparameter search using TimeSeriesSplit CV,
    then retrain on ALL data with best params for the final forecast.
    """
    try:
        import optuna
        optuna.logging.set_verbosity(optuna.logging.WARNING)
    except ImportError:
        raise ValueError("Optuna is not installed. Run: pip install optuna")

    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import TimeSeriesSplit

    arr = np.array(values, dtype=float)
    n = len(arr)
    lookback = max(2, min(int(base_hp.get("lookback", 5)), n // 3))
    forecast_steps = max(1, min(int(base_hp.get("forecast_steps", 20)), 500))
    test_split = max(0.1, min(float(base_hp.get("test_split", 0.2)), 0.5))
    n_trials = max(5, min(int(base_hp.get("n_trials", 30)), 100))

    # Linear has no hyperparams to tune
    if model_name == "linear":
        result = predict(values, labels, model_name, base_hp)
        result["best_params"] = {}
        result["best_trial_mae"] = result["metrics"]["mae"]
        return result

    X, y = _make_windows(arr, lookback)
    if len(X) < 5:
        raise ValueError(f"Not enough data for lookback={lookback}.")

    # TimeSeriesSplit: 3 folds for robustness
    n_splits = min(3, len(X) // 4)
    tscv = TimeSeriesSplit(n_splits=max(2, n_splits))

    def objective(trial: Any) -> float:
        hp = _suggest_params(trial, model_name)
        trial.set_user_attr("processed_hp", hp)
        fold_maes = []
        for train_idx, val_idx in tscv.split(X):
            X_tr, y_tr = X[train_idx], y[train_idx]
            X_vl, y_vl = X[val_idx], y[val_idx]
            sx = StandardScaler()
            sy = StandardScaler()
            X_tr_s = sx.fit_transform(X_tr)
            y_tr_s = sy.fit_transform(y_tr.reshape(-1, 1)).ravel()
            try:
                m = _build_model(model_name, hp)
                m.fit(X_tr_s, y_tr_s)
                X_vl_s = sx.transform(X_vl)
                pred_s = m.predict(X_vl_s)
                pred = sy.inverse_transform(pred_s.reshape(-1, 1)).ravel()
                fold_maes.append(float(np.mean(np.abs(pred - y_vl))))
            except Exception:
                return float("inf")
        return float(np.mean(fold_maes)) if fold_maes else float("inf")

    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=n_trials, show_progress_bar=False)

    best_processed = study.best_trial.user_attrs.get("processed_hp", {})

    # ── Retrain on ALL windows with best hyperparams ─────────────────────────
    # This is the key step: tune on splits, but fit the final model on
    # the entire dataset so the forecast benefits from all available data.
    scaler_X_full = StandardScaler()
    scaler_y_full = StandardScaler()
    X_all_s = scaler_X_full.fit_transform(X)
    y_all_s = scaler_y_full.fit_transform(y.reshape(-1, 1)).ravel()

    final_model = _build_model(model_name, best_processed)
    final_model.fit(X_all_s, y_all_s)

    # Metrics on the held-out test portion (same split as untuned predict)
    split_idx = max(2, int(len(X) * (1 - test_split)))
    X_test_s = scaler_X_full.transform(X[split_idx:])
    if len(X_test_s) > 0:
        test_preds_s = final_model.predict(X_test_s)
        test_preds = scaler_y_full.inverse_transform(
            test_preds_s.reshape(-1, 1)
        ).ravel()
        metrics = _compute_metrics(y[split_idx:], test_preds)
    else:
        metrics = _compute_metrics(np.array([]), np.array([]))

    # Recursive future forecast from the last `lookback` real values
    last_window = arr[-lookback:].tolist()
    future_values: list[float] = []
    for _ in range(forecast_steps):
        w = np.array(last_window[-lookback:]).reshape(1, -1)
        w_s = scaler_X_full.transform(w)
        p_s = final_model.predict(w_s)
        p = float(scaler_y_full.inverse_transform(p_s.reshape(-1, 1)).ravel()[0])
        future_values.append(round(p, 4))
        last_window.append(p)

    future_labels = [f"T+{i + 1}" for i in range(forecast_steps)]

    return {
        "future_predictions": [
            {"x_label": lbl, "value": v}
            for lbl, v in zip(future_labels, future_values)
        ],
        "metrics": metrics,
        "original_values": [round(float(v), 4) for v in arr],
        "original_labels": labels,
        "lookback": int(lookback),
        "best_params": best_processed,
        "best_trial_mae": round(study.best_value, 4),
    }


def _compute_metrics(y_true: np.ndarray, y_pred: np.ndarray) -> dict:
    """Compute comprehensive regression metrics."""
    if len(y_true) < 2:
        return {
            "mae": 0.0, "mse": 0.0, "rmse": 0.0, "r2": 0.0,
            "mape": 0.0, "explained_variance": 0.0,
            "max_error": 0.0, "median_ae": 0.0, "directional_accuracy": 0.0,
        }

    residuals = y_pred - y_true
    mae = float(np.mean(np.abs(residuals)))
    mse = float(np.mean(residuals ** 2))
    rmse = float(np.sqrt(mse))

    ss_res = float(np.sum(residuals ** 2))
    ss_tot = float(np.sum((y_true - np.mean(y_true)) ** 2))
    r2 = round(1.0 - ss_res / ss_tot, 4) if ss_tot > 0 else 0.0

    nonzero = y_true != 0
    mape = (
        float(np.mean(np.abs(residuals[nonzero] / y_true[nonzero])) * 100)
        if np.any(nonzero) else 0.0
    )

    # Explained Variance Score = 1 - Var(y_true - y_pred) / Var(y_true)
    var_true = float(np.var(y_true))
    var_residual = float(np.var(residuals))
    ev = round(1.0 - var_residual / var_true, 4) if var_true > 0 else 0.0

    max_err = float(np.max(np.abs(residuals)))
    median_ae = float(np.median(np.abs(residuals)))

    # Directional accuracy: % of steps where predicted direction == actual direction
    if len(y_true) > 1:
        actual_dir = np.sign(np.diff(y_true))
        pred_dir = np.sign(np.diff(y_pred))
        dir_acc = float(np.mean(actual_dir == pred_dir) * 100)
    else:
        dir_acc = 0.0

    return {
        "mae": round(mae, 4),
        "mse": round(mse, 4),
        "rmse": round(rmse, 4),
        "r2": round(r2, 4),
        "mape": round(mape, 2),
        "explained_variance": round(ev, 4),
        "max_error": round(max_err, 4),
        "median_ae": round(median_ae, 4),
        "directional_accuracy": round(dir_acc, 2),
    }


def predict(
    values: list[float],
    labels: list[str],
    model_name: str,
    hyperparams: dict,
) -> dict:
    from sklearn.preprocessing import StandardScaler

    arr = np.array(values, dtype=float)
    n = len(arr)

    lookback = max(2, min(int(hyperparams.get("lookback", 5)), n // 3))
    forecast_steps = max(1, min(int(hyperparams.get("forecast_steps", 20)), 500))
    test_split = max(0.1, min(float(hyperparams.get("test_split", 0.2)), 0.5))

    X, y = _make_windows(arr, lookback)
    if len(X) < 5:
        raise ValueError(
            f"Not enough data for lookback={lookback}. Need at least {lookback + 5} points."
        )

    split_idx = max(2, int(len(X) * (1 - test_split)))
    X_train, y_train = X[:split_idx], y[:split_idx]
    X_test, y_test = X[split_idx:], y[split_idx:]

    scaler_X = StandardScaler()
    scaler_y = StandardScaler()
    X_train_s = scaler_X.fit_transform(X_train)
    y_train_s = scaler_y.fit_transform(y_train.reshape(-1, 1)).ravel()

    model = _build_model(model_name, hyperparams)
    model.fit(X_train_s, y_train_s)

    test_preds = np.array([])
    if len(X_test) > 0:
        X_test_s = scaler_X.transform(X_test)
        test_preds_s = model.predict(X_test_s)
        test_preds = scaler_y.inverse_transform(
            test_preds_s.reshape(-1, 1)
        ).ravel()

    metrics = _compute_metrics(y_test, test_preds) if len(test_preds) > 1 else _compute_metrics(np.array([]), np.array([]))

    last_window = arr[-lookback:].tolist()
    future_values: list[float] = []
    for _ in range(forecast_steps):
        w = np.array(last_window[-lookback:]).reshape(1, -1)
        w_s = scaler_X.transform(w)
        p_s = model.predict(w_s)
        p = float(scaler_y.inverse_transform(p_s.reshape(-1, 1)).ravel()[0])
        future_values.append(round(p, 4))
        last_window.append(p)

    future_labels = [f"T+{i + 1}" for i in range(forecast_steps)]

    return {
        "future_predictions": [
            {"x_label": lbl, "value": v}
            for lbl, v in zip(future_labels, future_values)
        ],
        "metrics": metrics,
        "original_values": [round(float(v), 4) for v in arr],
        "original_labels": labels,
        "lookback": int(lookback),
    }
